import type { Recipe, RecipeSummary } from "./types";

export const mockRecipe: Recipe = {
  id: "xihongshi-chaodan",
  title: "西红柿炒鸡蛋",
  summary: "家常经典，酸甜咸鲜，十分钟搞定，百吃不厌。",
  difficulty: 1,
  calories: 180,
  duration_min: 10,
  category: "家常菜",
  cover_image: "",
  tags: ["快手", "下饭", "新手友好"],
  ingredients: [
    { name: "西红柿", amount: "2个（约400g）", per_serving: true },
    { name: "鸡蛋", amount: "3个", per_serving: true },
    { name: "食盐", amount: "适量" },
    { name: "白糖", amount: "1/2茶匙" },
    { name: "食用油", amount: "2汤匙" },
    { name: "葱花", amount: "少许", optional: true },
  ],
  tools: ["炒锅", "锅铲", "碗"],
  servings: {
    base: 2,
    formula: [
      { name: "西红柿", expr: "2个 × (份数/2)" },
      { name: "鸡蛋", expr: "3个 × (份数/2)" },
    ],
  },
  steps: [
    {
      index: 1,
      title: "打散鸡蛋",
      instruction: "将鸡蛋打入碗中，加一小撮盐，用筷子充分打散至无蛋白絮。",
      duration_sec: 60,
      produces: "蛋液",
      tips: ["打散要彻底，蛋液颜色均匀，炒出来更嫩"],
    },
    {
      index: 2,
      title: "切西红柿",
      instruction: "西红柿洗净，去蒂，切成月牙形滚刀块，约1.5cm厚。",
      duration_sec: 90,
      produces: "西红柿块",
      tips: ["不要切太小，炒后会软烂缩水"],
    },
    {
      index: 3,
      title: "炒鸡蛋",
      instruction: "锅烧热后倒入1汤匙油，油热至微微冒烟时倒入蛋液。等底部凝固后用铲子推成大块，蛋刚熟即出锅备用。",
      duration_sec: 60,
      produces: "炒蛋块",
      tips: ["油要够热才能炒出嫩滑的蛋", "不要过度翻炒，保留大块感"],
    },
    {
      index: 4,
      title: "炒西红柿",
      instruction: "原锅再加1汤匙油，下西红柿块中火翻炒约2分钟，炒出汁水。",
      duration_sec: 120,
      produces: "炒软的西红柿",
    },
    {
      index: 5,
      title: "合炒调味",
      instruction: "倒回炒蛋块，加盐和白糖翻炒均匀，尝味后出锅，撒葱花装盘。",
      duration_sec: 30,
      tips: ["糖是提鲜的，不会有明显甜味，不要省", "最后大火翻炒10秒收汁"],
    },
  ],
  variants: [
    { title: "加番茄酱", desc: "步骤4下1勺番茄酱，颜色更红亮、味道更浓郁" },
    { title: "嫩滑版", desc: "蛋液加少许水淀粉，口感更嫩滑" },
  ],
  tips: ["西红柿选熟透发软的，汁水足", "全程中大火，锅气足才好吃"],
};

export const mockRecipeList: RecipeSummary[] = [
  {
    id: "xihongshi-chaodan",
    title: "西红柿炒鸡蛋",
    category: "家常菜",
    cover_image: "",
    summary: "酸甜咸鲜，十分钟搞定",
    difficulty: 1,
    calories: 180,
    duration_min: 10,
    tags: ["快手", "新手友好"],
  },
  {
    id: "gongbao-jiding",
    title: "宫保鸡丁",
    category: "川菜",
    cover_image: "",
    summary: "麻辣鲜香，下饭神器",
    difficulty: 3,
    calories: 320,
    duration_min: 25,
    tags: ["下饭", "川菜"],
  },
  {
    id: "hongshao-rou",
    title: "红烧肉",
    category: "家常菜",
    cover_image: "",
    summary: "肥而不腻，入口即化",
    difficulty: 3,
    calories: 480,
    duration_min: 90,
    tags: ["硬菜", "招待"],
  },
  {
    id: "mapo-doufu",
    title: "麻婆豆腐",
    category: "川菜",
    cover_image: "",
    summary: "麻辣烫口，豆腐嫩滑",
    difficulty: 2,
    calories: 220,
    duration_min: 20,
    tags: ["快手", "下饭", "川菜"],
  },
  {
    id: "qingzheng-luyu",
    title: "清蒸鲈鱼",
    category: "粤菜",
    cover_image: "",
    summary: "鲜嫩清甜，原汁原味",
    difficulty: 2,
    calories: 150,
    duration_min: 30,
    tags: ["清淡", "健康"],
  },
  {
    id: "yangcong-chaoniurou",
    title: "洋葱炒牛肉",
    category: "家常菜",
    cover_image: "",
    summary: "鲜嫩多汁，越嚼越香",
    difficulty: 2,
    calories: 290,
    duration_min: 15,
    tags: ["快手", "下饭"],
  },
];
