import type { Recipe, RecipeSummary } from "./types";

export const mockRecipe: Recipe = {
  id: "xihongshi-chaodan",
  title: "西红柿炒鸡蛋",
  summary: "一道酸甜开胃的家常菜肴,嫩滑的鸡蛋裹着软烂多汁的西红柿,是中国家庭餐桌上的经典味道。鸡蛋提供优质蛋白质,西红柿富含维生素 C 和番茄红素,营养均衡好吸收。步骤简单,原材料易得,特别适合厨房新手入门,从头备菜到盛盘出锅大约只需 15 分钟。",
  difficulty: 1,
  calories: 252,
  duration_min: 15,
  category: "家常菜",
  cover_image: "",
  overview_image: "/recipes/overview-guide.jpg",
  tags: ["快手", "下饭", "新手友好"],
  ingredients: [
    { name: "西红柿", amount: "1个(约180g)", per_serving: true },
    { name: "鸡蛋", amount: "1.5个", per_serving: true },
    { name: "食用油", amount: "4ml/个鸡蛋", per_serving: true },
    { name: "盐", amount: "1.5-2g", per_serving: true },
    { name: "糖", amount: "0-2g", per_serving: true, optional: true },
    { name: "葱花", amount: "0-10g", per_serving: true, optional: true },
  ],
  tools: ["炒锅", "锅铲", "碗"],
  servings: {
    base: 1,
    formula: [
      { name: "西红柿", expr: "1个(约180g) × 份数" },
      { name: "鸡蛋", expr: "1.5个 × 份数,向上取整" },
      { name: "食用油", expr: "4ml × 鸡蛋数量" },
      { name: "盐", expr: "1.5-2g × 份数" },
      { name: "糖", expr: "0-2g × 份数" },
      { name: "葱花", expr: "0-10g × 份数" },
    ],
  },
  steps: [
    {
      index: 1,
      title: "西红柿洗净",
      instruction: "将西红柿用清水冲洗干净。",
      duration_sec: 30,
    },
    {
      index: 2,
      title: "可选:去掉西红柿的外表皮",
      instruction: "开水烫表皮,然后将西红柿放入冷水,剥去外皮。",
      duration_sec: 120,
      tips: ["这一步可以省略,不去皮也不影响口感"],
    },
    {
      index: 3,
      title: "西红柿切块",
      instruction: "西红柿去蒂,切成边长不超过4cm的小块。",
      duration_sec: 60,
      produces: "西红柿块",
    },
    {
      index: 4,
      title: "打散鸡蛋",
      instruction: "将鸡蛋打入碗中,加入1g × 份数的盐,搅匀。",
      duration_sec: 60,
      produces: "鸡蛋液",
      tips: ["可以考虑向鸡蛋中加入1ml醋,这可以去除腥味,令鸡蛋更蓬松"],
    },
    {
      index: 5,
      title: "热锅加油",
      instruction: "热锅,加入食用油。",
      duration_sec: 30,
    },
    {
      index: 6,
      title: "炒鸡蛋",
      instruction: "油热后,倒入鸡蛋液。翻炒至鸡蛋结为固体且颜色微微发黄。",
      duration_sec: 60,
      produces: "半熟鸡蛋",
    },
    {
      index: 7,
      title: "盛出鸡蛋",
      instruction: "关火。将半熟鸡蛋盛盘,重新开火。",
      duration_sec: 20,
      tips: ["注意:不要洗锅"],
    },
    {
      index: 8,
      title: "炒西红柿",
      instruction: "加入西红柿块,锅铲拍打并翻炒20秒,或至西红柿软烂。",
      duration_sec: 30,
      tips: ["可以考虑加入10ml番茄酱和50ml清水,增加汤汁"],
    },
    {
      index: 9,
      title: "合炒",
      instruction: "向锅中加入半熟鸡蛋,翻炒均匀。",
      duration_sec: 30,
      tips: ["可以额外加入一些其它熟肉和材料"],
    },
    {
      index: 10,
      title: "调味出锅",
      instruction: "加入剩余的盐、糖(可选)、葱花(可选),翻炒均匀。关火,盛盘。",
      duration_sec: 30,
    },
  ],
  variants: [
    {
      title: "快速做法",
      desc: "直接在有半熟鸡蛋的锅中加入西红柿块,与鸡蛋一起翻炒直至西红柿软烂,然后继续第10步。"
    },
    {
      title: "生抽版本",
      desc: "加入盐改为加入两滴生抽。"
    },
  ],
  tips: [
    "西红柿选熟透发软的,汁水足",
    "如果您遵循本指南的制作流程而发现有问题或可以改进的流程,请提出 Issue 或 Pull request"
  ],
};

export const mockRecipeList: RecipeSummary[] = [
  {
    id: "xihongshi-chaodan",
    title: "西红柿炒鸡蛋",
    category: "家常菜",
    cover_image: "",
    summary: "酸甜咸鲜十五分钟搞定的经典家常菜，嫩滑鸡蛋裹着多汁西红柿，营养均衡好吸收",
    difficulty: 1,
    calories: 252,
    duration_min: 15,
    tags: ["快手", "新手友好"],
  },
  {
    id: "gongbao-jiding",
    title: "宫保鸡丁",
    category: "川菜",
    cover_image: "",
    summary: "麻辣鲜香的川菜经典，鸡丁外焦里嫩搭配花生米，层次丰富是下饭神器",
    difficulty: 3,
    calories: 320,
    duration_min: 25,
    tags: ["下饭", "川菜"],
  },
  {
    id: "hongshao-rou",
    title: "红烧肉",
    category: "家常菜",
    cover_image: "",
    summary: "肥而不腻入口即化的硬菜担当，红亮的色泽配上浓郁的酱香，招待客人的不二之选",
    difficulty: 3,
    calories: 480,
    duration_min: 90,
    tags: ["硬菜", "招待"],
  },
  {
    id: "mapo-doufu",
    title: "麻婆豆腐",
    category: "川菜",
    cover_image: "",
    summary: "麻辣烫口豆腐嫩滑的川菜代表，麻婆豆腐讲究麻辣鲜香烫酥嫩，快手又下饭",
    difficulty: 2,
    calories: 220,
    duration_min: 20,
    tags: ["快手", "下饭", "川菜"],
  },
  {
    id: "qingzheng-luyu",
    title: "清蒸鲈鱼",
    category: "粤菜",
    cover_image: "",
    summary: "鲜嫩清甜原汁原味的粤式做法，保留食材本真滋味，清淡健康适合养生",
    difficulty: 2,
    calories: 150,
    duration_min: 30,
    tags: ["清淡", "健康"],
  },
  {
    id: "yangcong-chaoniurou",
    title: "洋葱炒牛肉",
    category: "家常菜",
    cover_image: "",
    summary: "鲜嫩多汁越嚼越香的快手硬菜，牛肉滑嫩洋葱爽脆，十五分钟出锅",
    difficulty: 2,
    calories: 290,
    duration_min: 15,
    tags: ["快手", "下饭"],
  },
];